### ISSUE TITLE
Add a suffix

### ISSUE THREAD

**Issue by gmmedia** [webchun/foundation-6-sublime-autocomplete#1]
Nice plugin idea.

What do you think about a suffix, like "zf-"?

**Comment by webchun** [comment]
Hi, thanks. But the idea is about the ‘autocomplete' function, not for code snippets so it doesn't need a custom suffix to trigger it. If you’re looking for a zurb foundation snippets, I think there’s already a plugin for that available in the package control.
I use this plugin mainly to remind me foundation classes name while coding
